services:
  web:
    build: .
    container_name: AspMVC
    ports:
      - "8080:8080" 
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=AspMVC;Username=postgres;Password=example"
    volumes:
      - ./wwwroot/uploads:/app/wwwroot/uploads

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: AspMVC
    ports:
      - "5432:5432"   # если нужен доступ с хоста (RadminVPN)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
